Repository railwayapp/nixpacks, pull requests merged in 2022-09, with the labels that each got.

#440 Auto Publish Nixpacks using Labels
  .github/workflows/label-check.yml
  .github/workflows/tag.yml
Labels: release/patch, stale

#516 Fix quotes on autopub
  .github/workflows/tag.yml
Labels: release/patch

#515 Exclude check step from Gradle build
  src/providers/java.rs
  tests/snapshots/generate_plan_tests__java_gradle_hello_world.snap
  tests/snapshots/generate_plan_tests__java_spring_boot.snap
Labels: release/patch

#517 Committer Token
  .github/workflows/tag.yml
Labels: release/patch

#518 Log output of action
  .github/workflows/tag.yml
Labels: release/patch

#519 Dry run with correct comparison
  .github/workflows/tag.yml
Labels: release/patch

#520 Automated releases
  .github/workflows/tag.yml
Labels: release/patch

#521 Correctly invoke cargo in a single line
  .github/workflows/tag.yml
Labels: release/patch

#522 Use different action for publishing release
  .github/workflows/label-check.yml
  .github/workflows/tag.yml
Labels: release/patch

#523 Use action-rs/cargo (again)
  .github/workflows/label-check.yml
  .github/workflows/tag.yml
Labels: release/patch

#524 Invoke run raw
  .github/workflows/tag.yml
Labels: release/patch

#525 no-confirm for auto publish
  .github/workflows/tag.yml
Labels: release/patch

#526 Set Actions User
  .github/workflows/tag.yml
Labels: release/patch

#527 Authenticate as Railway Bot
  .github/workflows/tag.yml
  Cargo.lock
  Cargo.toml
Labels: release/patch

#528 PAT release
  .github/workflows/tag.yml
  Cargo.lock
  Cargo.toml
Labels: release/patch

#529 Use PAT on checkout
  .github/workflows/tag.yml
Labels: release/patch

#530 Don't retrigger releases
  .github/workflows/tag.yml
Labels: release/patch

#531 Ignore gitignored files
  Cargo.lock
  Cargo.toml
  src/nixpacks/app.rs
  src/nixpacks/files.rs
Labels: release/minor

#532 Decrease base image size
  base/debian/Dockerfile
  src/nixpacks/plan/merge.rs
  src/nixpacks/plan/mod.rs
Labels: release/patch

#544 Allow skipping automatic releases
  .github/workflows/bump-version-flake.yml
  .github/workflows/label-check.yml
  .github/workflows/publish_debian.yml
  .github/workflows/tag.yml
Labels: release/skip

#534 Cache rust dependencies in tag workflow
  .github/workflows/tag.yml
Labels: release/skip

#545 disable all standard filters by default with ignore
  src/nixpacks/files.rs
Labels: release/patch

#547 Error if no start phase or start command
  src/lib.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
Labels: release/patch

#548 Wait for tests before tagging
  .github/workflows/tag.yml
Labels: release/skip

#549 Allow specifying location of config file with env var
  docs/pages/docs/cli.md
  docs/pages/docs/configuration/environment.md
  docs/pages/docs/configuration/file.md
  src/nixpacks/plan/generator.rs
Labels: release/patch

#560 feat: enable `RAILS_LOG_TO_STDOUT`
  src/providers/ruby.rs
  tests/snapshots/generate_plan_tests__ruby_rails_postgres.snap
Labels: release/patch

#562 Improve tagging CI
  .github/workflows/ci.yml
  .github/workflows/tag.yml
Labels: release/skip

#552 fix: allow targets without a options attribute
  examples/node-nx/apps/no-options/astro.config.mjs
  examples/node-nx/apps/no-options/project.json
  examples/node-nx/apps/no-options/public/assets/logo.svg
  examples/node-nx/apps/no-options/public/favicon.ico
  examples/node-nx/apps/no-options/public/robots.txt
  examples/node-nx/apps/no-options/public/styles/global.css
  examples/node-nx/apps/no-options/public/styles/home.css
  examples/node-nx/apps/no-options/src/components/Tour.astro
  examples/node-nx/apps/no-options/src/pages/index.astro
  examples/node-nx/apps/no-options/tsconfig.json
  examples/node-nx/apps/node-app/project.json
  examples/node-nx/apps/start-command-production/project.json
  examples/node-nx/apps/start-command/project.json
  examples/node-nx/nx.json
  examples/node-nx/package-lock.json
  examples/node-nx/package.json
  examples/node-nx/tools/scripts/patch-nx-cli.js
  examples/node-nx/workspace.json
  src/providers/node/mod.rs
  src/providers/node/nx.rs
  tests/docker_run_tests.rs
Labels: release/patch

#567 Correct buildImage in docs
  docs/pages/docs/configuration/file.md
Labels: release/skip

#570 Do not take .gitignore into consideration when copying to temp dir
  src/nixpacks/files.rs
Labels: bug, release/minor

#577 Fix cache from argument
  src/main.rs
Labels: bug, release/patch

#572 Add bun to the Node docs
  docs/pages/docs/providers/node.md
Labels: release/skip

#579 Default path to current dir
  src/main.rs
  src/providers/php/mod.rs
Labels: release/minor

#584 Add `release/patch` on update-nixpkgs-archive workflow
  .github/workflows/update-nixpkgs-archive.yml
Labels: release/skip

#586 Optimize installation of packages
  .github/workflows/update-nixpkgs-archive.yml
  src/lib.rs
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/nixpacks/nix/mod.rs
  src/nixpacks/plan/generator.rs
  src/nixpacks/plan/phase.rs
Labels: release/minor

#593 Add `libicu-dev` if `charlock_holmes` is detected
  src/providers/ruby.rs
Labels: release/patch

#594 Configuring builds guide
  docs/pages/docs/configuration/file.md
  docs/pages/docs/guides/configuring-builds.md
  docs/sidebar.ts
Labels: release/skip

#596 Add `release/skip` to dependabot PRs
  .github/dependabot.yml
Labels: release/skip
