Repository railwayapp/nixpacks, pull requests merged in 2022-10, with the labels that each got.

#598 fix(install): update PATH envvar on pwsh script
  install.ps1
Labels: release/skip

#597 Python psycopg2 and postgres
  examples/python-postgres/main.py
  examples/python-postgres/requirements.txt
  src/providers/python.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__python_postgres.snap
Labels: release/patch

#599 use absolute paths for compatibility with podman
  src/nixpacks/builder/docker/utils.rs
Labels: release/patch

#606 ruby: auto install nodejs if execjs used, and auto install imagemagic dependencies
  src/providers/ruby.rs
Labels: release/patch

#605 Install additional packages when node-gyp or node-pre-gyp packages are present
  .cargo/config
  examples/node-canvas/index.js
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_canvas.snap
  tests/snapshots/generate_plan_tests__node_nx.snap
  tests/snapshots/generate_plan_tests__node_yarn_berry.snap
Labels: release/patch

#553 Incremental caching
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  README.md
  docs/pages/docs/install.md
  src/main.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/nixpacks/builder/docker/file_server.rs
  src/nixpacks/builder/docker/incremental_cache.rs
  src/nixpacks/builder/docker/mod.rs
  src/providers/java.rs
  tests/snapshots/generate_plan_tests__java_gradle_hello_world.snap
  tests/snapshots/generate_plan_tests__java_spring_boot.snap
Labels: release/minor

#612 provider(java): make mvnw executable
  src/providers/java.rs
  tests/snapshots/generate_plan_tests__java_maven_wrapper.snap
Labels: release/patch

#613 Revert "Install additional packages when node-gyp or node-pre-gyp packages are present (#605)"
  .cargo/config
  examples/node-canvas/index.js
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_canvas.snap
  tests/snapshots/generate_plan_tests__node_nx.snap
  tests/snapshots/generate_plan_tests__node_yarn_berry.snap
Labels: release/patch

#615 add support to install a specific nixpacks version with NIXPACKS_VERSION
  install.sh
Labels: release/skip

#617 Install nodejs only once for the Ruby provider
  examples/ruby-execjs/Gemfile
  examples/ruby-execjs/Gemfile.lock
  examples/ruby-execjs/Procfile
  examples/ruby-execjs/app.rb
  src/providers/node/mod.rs
  src/providers/php/mod.rs
  src/providers/ruby.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__ruby_execjs.snap
Labels: release/patch

#622 fix: get version from .yarnrc.yml
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_yarn_berry.snap
Labels: release/patch

#629 only create the incremental cache dirs if the feature is enabled
  src/nixpacks/builder/docker/docker_image_builder.rs
  src/nixpacks/builder/docker/incremental_cache.rs
Labels: release/patch

#557 Turborepo support
  docs/pages/docs/providers/node.md
  examples/node-turborepo/.eslintrc.js
  examples/node-turborepo/.gitignore
  examples/node-turborepo/README.md
  examples/node-turborepo/apps/docs/.eslintrc.js
  examples/node-turborepo/apps/docs/README.md
  examples/node-turborepo/apps/docs/next-env.d.ts
  examples/node-turborepo/apps/docs/next.config.js
  examples/node-turborepo/apps/docs/package.json
  examples/node-turborepo/apps/docs/pages/index.tsx
  examples/node-turborepo/apps/docs/tsconfig.json
  examples/node-turborepo/apps/web/.eslintrc.js
  examples/node-turborepo/apps/web/README.md
  examples/node-turborepo/apps/web/next-env.d.ts
  examples/node-turborepo/apps/web/next.config.js
  examples/node-turborepo/apps/web/package.json
  examples/node-turborepo/apps/web/pages/index.tsx
  examples/node-turborepo/apps/web/tsconfig.json
  examples/node-turborepo/package-lock.json
  examples/node-turborepo/package.json
  examples/node-turborepo/packages/eslint-config-custom/index.js
  examples/node-turborepo/packages/eslint-config-custom/package.json
  examples/node-turborepo/packages/tsconfig/README.md
  examples/node-turborepo/packages/tsconfig/base.json
  examples/node-turborepo/packages/tsconfig/nextjs.json
  examples/node-turborepo/packages/tsconfig/package.json
  examples/node-turborepo/packages/tsconfig/react-library.json
  examples/node-turborepo/packages/ui/Button.tsx
  examples/node-turborepo/packages/ui/index.tsx
  examples/node-turborepo/packages/ui/package.json
  examples/node-turborepo/packages/ui/tsconfig.json
  examples/node-turborepo/turbo.json
  src/providers/node/mod.rs
  src/providers/node/turborepo.rs
  tests/docker_run_tests.rs
  tests/generate_plan_tests.rs
  tests/snapshots/generate_plan_tests__node_turborepo.snap
Labels: new provider, release/minor

#627 Fix usage of cache dirs env vars
  src/nixpacks/plan/mod.rs
  tests/snapshots/generate_plan_tests__config_from_environment_variables.snap
Labels: release/minor

#628 Include no files in ruby setup phase
  src/providers/ruby.rs
  tests/snapshots/generate_plan_tests__ruby.snap
  tests/snapshots/generate_plan_tests__ruby_execjs.snap
  tests/snapshots/generate_plan_tests__ruby_local_deps.snap
  tests/snapshots/generate_plan_tests__ruby_rails_postgres.snap
  tests/snapshots/generate_plan_tests__ruby_sinatra.snap
  tests/snapshots/generate_plan_tests__ruby_with_node.snap
Labels: release/minor

#634 support any package.json workspaces value
  src/providers/node/mod.rs
  src/providers/node/turborepo.rs
Labels: release/patch

#635 Prefer web procfile process
  examples/python-procfile/Procfile
  src/providers/procfile.rs
Labels: release/patch

#636 Basic support for .nvmrc files
  examples/node-nvmrc/.nvmrc
  examples/node-nvmrc/index.js
  examples/node-nvmrc/package-lock.json
  examples/node-nvmrc/package.json
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_nvmrc.snap
Labels: release/minor

#637 Remove tag action for now
  .github/workflows/tag.yml
Labels: release/skip
