Repository railwayapp/nixpacks, pull requests merged in 2022-12, with the labels that each got.

#698 Remove 7.4 from PHP supported versions in docs
  docs/pages/docs/providers/php.md
Labels: release/skip

#699 Add workflow to push Nixpacks base image to docker hub
  .github/workflows/publish_debian.yml
Labels: release/skip

#685 Support copy files to a subdirectory in app directory
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/nixpacks/builder/docker/utils.rs
  src/providers/ruby.rs
  src/providers/rust.rs
  tests/generate_plan_tests.rs
  tests/snapshots/generate_plan_tests__ruby.snap
  tests/snapshots/generate_plan_tests__ruby_execjs.snap
  tests/snapshots/generate_plan_tests__ruby_rails_postgres.snap
  tests/snapshots/generate_plan_tests__ruby_sinatra.snap
  tests/snapshots/generate_plan_tests__ruby_with_node.snap
Labels: release/minor

#710 Update java.md
  docs/pages/docs/providers/java.md
Labels: release/skip

#713 Install openssl from nixpkgs if prisma is detected
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_prisma_postgres.snap
  tests/snapshots/generate_plan_tests__node_turborepo.snap
  tests/snapshots/generate_plan_tests__node_yarn_prisma.snap
Labels: release/minor

#715 noninteractive debian frontend and install tzdata
  base/ubuntu/Dockerfile
Labels: release/skip

#717 Add Corepack docs
  docs/pages/docs/providers/node.md
Labels: release/skip

#720 Apply updated clippy fixes
  src/nixpacks/app.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/nixpacks/builder/docker/file_server.rs
  src/nixpacks/builder/docker/incremental_cache.rs
  src/nixpacks/builder/docker/utils.rs
  src/nixpacks/environment.rs
  src/nixpacks/logger.rs
  src/nixpacks/nix/mod.rs
  src/nixpacks/nix/pkg.rs
  src/nixpacks/plan/generator.rs
  src/nixpacks/plan/mod.rs
  src/nixpacks/plan/phase.rs
  src/nixpacks/plan/pretty_print.rs
  src/providers/clojure.rs
  src/providers/cobol.rs
  src/providers/csharp.rs
  src/providers/fsharp.rs
  src/providers/go.rs
  src/providers/haskell.rs
  src/providers/java.rs
  src/providers/node/mod.rs
  src/providers/node/nx.rs
  src/providers/node/turborepo.rs
  src/providers/php/mod.rs
  src/providers/python.rs
  src/providers/ruby.rs
  src/providers/rust.rs
  src/providers/staticfile.rs
  src/providers/swift.rs
  src/providers/zig.rs
Labels: release/skip

#719 do not use corepack for node 14
  docs/pages/docs/providers/node.md
  src/providers/node/mod.rs
Labels: release/patch

#716 Fix Rust custom toolchain file support
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/nixpacks/nix/mod.rs
  src/providers/rust.rs
  tests/docker_run_tests.rs
Labels: release/patch

#723 Pass the nixpacks.toml variables to the providers
  examples/go-cgo-enabled/nixpacks.toml
  examples/go-cgo-enabled/test.env
  src/nixpacks/environment.rs
  src/nixpacks/plan/generator.rs
Labels: release/patch

#712 Default to Ubuntu base image
  src/nixpacks/images.rs
  src/nixpacks/nix/mod.rs
  src/nixpacks/plan/generator.rs
  src/nixpacks/plan/mod.rs
  src/nixpacks/plan/phase.rs
  src/providers/clojure.rs
  tests/snapshots/generate_plan_tests__clojure.snap
  tests/snapshots/generate_plan_tests__clojure_jdk11.snap
  tests/snapshots/generate_plan_tests__clojure_jdk_latest.snap
  tests/snapshots/generate_plan_tests__clojure_ring_app.snap
  tests/snapshots/generate_plan_tests__go.snap
  tests/snapshots/generate_plan_tests__go_custom_version.snap
  tests/snapshots/generate_plan_tests__go_gin.snap
  tests/snapshots/generate_plan_tests__go_mod.snap
Labels: release/major

#725 Java provider default jdk17 and custom versions
  docs/pages/docs/providers/java.md
  src/providers/java.rs
  tests/snapshots/generate_plan_tests__java_gradle_hello_world.snap
  tests/snapshots/generate_plan_tests__java_maven.snap
  tests/snapshots/generate_plan_tests__java_maven_wrapper.snap
  tests/snapshots/generate_plan_tests__java_spring_boot.snap
Labels: release/minor

#726 use debian base image for ruby 2
  Cargo.lock
  Cargo.toml
  examples/ruby-2/.ruby-version
  examples/ruby-2/Gemfile
  examples/ruby-2/Gemfile.lock
  examples/ruby-2/Procfile
  examples/ruby-2/app.rb
  src/nixpacks/nix/mod.rs
  src/providers/ruby.rs
  tests/snapshots/generate_plan_tests__ruby_2.snap
Labels: release/patch

#728 Docs: Add 8.2 to supported PHP versions
  docs/pages/docs/providers/php.md
Labels: release/skip

#732 Fix some wording in publish_ubuntu & publish_debian
  .github/workflows/publish_debian.yml
  .github/workflows/publish_ubuntu.yml
Labels: release/skip

#718 Add traits Send And Sync to the Provider type
  src/lib.rs
  src/nixpacks/plan/generator.rs
  src/providers/mod.rs
Labels: release/skip

#733 PNPM fixes
  .cargo/config.toml
  src/providers/node/mod.rs
  src/providers/node/nx.rs
  src/providers/node/turborepo.rs
  tests/snapshots/generate_plan_tests__node_pnpm.snap
  tests/snapshots/generate_plan_tests__node_pnpm_custom_node_version.snap
  tests/snapshots/generate_plan_tests__node_pnpm_v7.snap
Labels: release/patch

#739 Enable SSHD in codespace configuration
  .devcontainer/devcontainer.json
Labels: release/skip

#738 Bump dependencies
  Cargo.lock
  Cargo.toml
  src/providers/rust.rs
Labels: release/skip

#740 Use `cargo binstall` in codespace installation
  .devcontainer/library-scripts/rust-debian.sh
Labels: release/skip

#741 Fix cargo-binstall not installing in devcontainer configuration
  .devcontainer/library-scripts/rust-debian.sh
Labels: release/skip

#737 Bump default Poetry version
  src/providers/python.rs
  tests/snapshots/generate_plan_tests__python_poetry.snap
Labels: release/patch

#743 Use `cargo quickinstall` in `rust-debian.sh`
  .devcontainer/library-scripts/rust-debian.sh
Labels: release/skip

#744 Fix `rust-debian.sh`
  .devcontainer/library-scripts/rust-debian.sh
Labels: release/skip
