Repository railwayapp/nixpacks, pull requests merged in 2023-05, with the labels that each got.

#869 fix php provider cache issue
  src/providers/php/mod.rs
Labels: release/patch

#871 Add comments
  CONTRIBUTING.md
  src/lib.rs
  src/main.rs
  src/nixpacks/app.rs
  src/nixpacks/builder/docker/cache.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/nixpacks/builder/docker/file_server.rs
  src/nixpacks/builder/docker/incremental_cache.rs
  src/nixpacks/builder/docker/mod.rs
  src/nixpacks/builder/docker/utils.rs
  src/nixpacks/builder/mod.rs
  src/nixpacks/environment.rs
  src/nixpacks/files.rs
  src/nixpacks/logger.rs
  src/nixpacks/nix/mod.rs
  src/nixpacks/nix/pkg.rs
  src/nixpacks/plan/generator.rs
  src/nixpacks/plan/merge.rs
  src/nixpacks/plan/mod.rs
  src/nixpacks/plan/phase.rs
  src/nixpacks/plan/pretty_print.rs
  src/nixpacks/plan/topological_sort.rs
Labels: release/skip

#879 Create flightcontrol.md
  docs/pages/docs/deploying/flightcontrol.md
Labels: release/skip

#881 Add prettier for doc
  docs/.prettierignore
  docs/.prettierrc.js
  docs/components/Hero.tsx
  docs/components/SideNav.tsx
  docs/components/TableOfContents.tsx
  docs/components/TopNav.tsx
  docs/components/index.js
  docs/markdoc/nodes/fence.markdoc.ts
  docs/markdoc/nodes/index.ts
  docs/markdoc/tags/index.ts
  docs/next.config.js
  docs/package.json
  docs/pages/_app.tsx
  docs/pages/_document.tsx
  docs/pages/docs/providers/clojure.md
  docs/pages/docs/providers/cobol.md
  docs/pages/docs/providers/elixir.md
  docs/pages/docs/providers/php.md
  docs/postcss.config.js
  docs/public/prism-one-light.css
  docs/sidebar.ts
  docs/yarn.lock
Labels: release/skip

#883 Fix: use dvh to fix iOS sidebar style issue
  docs/components/SideNav.tsx
  docs/components/TableOfContents.tsx
  docs/components/TopNav.tsx
  docs/typings/styled-jsx.d.ts
Labels: release/skip

#873 Add provider `lunatic`
  docs/pages/docs/providers/lunatic.md
  docs/sidebar.ts
  examples/lunatic-basic/.cargo/config.toml
  examples/lunatic-basic/Cargo.toml
  examples/lunatic-basic/src/main.rs
  src/lib.rs
  src/providers/lunatic.rs
  src/providers/mod.rs
  src/providers/rust.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__lunatic_basic.snap
Labels: new provider, release/minor

#891 Fix doc build warning
  docs/components/SideNav.tsx
  docs/components/TableOfContents.tsx
  docs/package.json
  docs/yarn.lock
Labels: release/skip

#884 Fix: correct node version parse
  Cargo.lock
  Cargo.toml
  src/providers/node/mod.rs
Labels: release/minor

#895 add `runtime.txt` in the list of places to set the python version
  docs/pages/docs/providers/python.md
Labels: release/skip

#897 Gleam provider
  docs/pages/docs/providers/gleam.md
  examples/basic_gleam/.gitignore
  examples/basic_gleam/README.md
  examples/basic_gleam/gleam.toml
  examples/basic_gleam/manifest.toml
  examples/basic_gleam/src/basic_gleam.gleam
  src/lib.rs
  src/nixpacks/nix/pkg.rs
  src/providers/gleam/get-gleam.sh
  src/providers/gleam/mod.rs
  src/providers/mod.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__basic_gleam.snap
Labels: release/minor

#900 prepend PATH with NIXPACKS_PATH
  base/debian/Dockerfile
  base/ubuntu/Dockerfile
Labels: release/skip

#902 Prepend PATH during phase execution
  src/nixpacks/builder/docker/dockerfile_generation.rs
Labels: release/patch

#903 update ubuntu image to have "latest" tag
  .github/workflows/publish.yml
Labels: release/skip
