Repository railwayapp/nixpacks, pull requests merged in 2023-03, with the labels that each got.

#810 Better Perl parameter syntax
  src/providers/php/transform-config.pl
  tests/snapshots/generate_plan_tests__php_laravel.snap
  tests/snapshots/generate_plan_tests__php_vanilla.snap
Labels: release/patch

#804 feat(scala): added NIXPACKS_JDK_VERSION env
  docs/pages/docs/providers/scala.md
  src/providers/scala.rs
  tests/snapshots/generate_plan_tests__scala_sbt.snap
Labels: release/minor

#820 fix php provider
  src/providers/php/transform-config.pl
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__php_laravel.snap
  tests/snapshots/generate_plan_tests__php_vanilla.snap
Labels: release/patch

#829 Actually fix PHP extensions
  src/providers/php/mod.rs
  tests/snapshots/generate_plan_tests__php_custom_config.snap
  tests/snapshots/generate_plan_tests__php_laravel.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_mongodb.snap
  tests/snapshots/generate_plan_tests__php_vanilla.snap
Labels: release/patch

#842 Fix caching being busted by moving .profile update to end of build phase
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/providers/ruby.rs
  tests/snapshots/generate_plan_tests__ruby.snap
  tests/snapshots/generate_plan_tests__ruby_2.snap
  tests/snapshots/generate_plan_tests__ruby_execjs.snap
  tests/snapshots/generate_plan_tests__ruby_local_deps.snap
  tests/snapshots/generate_plan_tests__ruby_rails_postgres.snap
  tests/snapshots/generate_plan_tests__ruby_sinatra.snap
  tests/snapshots/generate_plan_tests__ruby_with_node.snap
Labels: release/minor

#839 Ruby on Rails: Do not run `rake assets:precompile` in build step if a Rails asset pipeline is not configured
  examples/ruby-rails-api-app/.gitattributes
  examples/ruby-rails-api-app/.gitignore
  examples/ruby-rails-api-app/.ruby-version
  examples/ruby-rails-api-app/Gemfile
  examples/ruby-rails-api-app/Gemfile.lock
  examples/ruby-rails-api-app/Procfile
  examples/ruby-rails-api-app/README.md
  examples/ruby-rails-api-app/Rakefile
  examples/ruby-rails-api-app/app/channels/application_cable/channel.rb
  examples/ruby-rails-api-app/app/channels/application_cable/connection.rb
  examples/ruby-rails-api-app/app/controllers/application_controller.rb
  examples/ruby-rails-api-app/app/controllers/concerns/.keep
  examples/ruby-rails-api-app/app/jobs/application_job.rb
  examples/ruby-rails-api-app/app/mailers/application_mailer.rb
  examples/ruby-rails-api-app/app/models/application_record.rb
  examples/ruby-rails-api-app/app/models/concerns/.keep
  examples/ruby-rails-api-app/app/views/layouts/mailer.html.erb
  examples/ruby-rails-api-app/app/views/layouts/mailer.text.erb
  examples/ruby-rails-api-app/bin/bundle
  examples/ruby-rails-api-app/bin/rails
  examples/ruby-rails-api-app/bin/rake
  examples/ruby-rails-api-app/bin/setup
  examples/ruby-rails-api-app/config.ru
  examples/ruby-rails-api-app/config/application.rb
  examples/ruby-rails-api-app/config/boot.rb
  examples/ruby-rails-api-app/config/cable.yml
  examples/ruby-rails-api-app/config/credentials.yml.enc
  examples/ruby-rails-api-app/config/database.yml
  examples/ruby-rails-api-app/config/environment.rb
  examples/ruby-rails-api-app/config/environments/development.rb
  examples/ruby-rails-api-app/config/environments/production.rb
  examples/ruby-rails-api-app/config/environments/test.rb
  examples/ruby-rails-api-app/config/initializers/cors.rb
  examples/ruby-rails-api-app/config/initializers/filter_parameter_logging.rb
  examples/ruby-rails-api-app/config/initializers/inflections.rb
  examples/ruby-rails-api-app/config/locales/en.yml
  examples/ruby-rails-api-app/config/puma.rb
  examples/ruby-rails-api-app/config/routes.rb
  examples/ruby-rails-api-app/config/storage.yml
  examples/ruby-rails-api-app/db/seeds.rb
  examples/ruby-rails-api-app/lib/tasks/.keep
  examples/ruby-rails-api-app/log/.keep
  examples/ruby-rails-api-app/public/robots.txt
  examples/ruby-rails-api-app/storage/.keep
  examples/ruby-rails-api-app/vendor/.keep
  src/providers/ruby.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__ruby_rails_api_app.snap
Labels: release/minor

#843 Improve Nix flake by adding checks, auto-updating version, and fixing build
  .github/workflows/ci.yml
  flake.lock
  flake.nix
  release.toml
Labels: release/skip

#844 fix snapshot tests after merge
  tests/snapshots/generate_plan_tests__ruby_rails_api_app.snap
Labels: release/patch
