Repository railwayapp/nixpacks, pull requests merged in 2023-09, with the labels that each got.

#958 Fix linting warnings with updated rust version
  src/main.rs
  src/nixpacks/plan/mod.rs
  src/providers/deno.rs
  src/providers/elixir.rs
  src/providers/java.rs
  src/providers/lunatic.rs
  src/providers/node/mod.rs
  src/providers/python.rs
  src/providers/ruby.rs
  src/providers/rust.rs
Labels: release/skip

#959 remove config file experimental warning
  docs/pages/docs/configuration/file.md
  src/nixpacks/plan/generator.rs
Labels: release/patch

#951 Add moon support to Node.js
  docs/pages/docs/providers/node.md
  examples/node-moon-monorepo/.moon/toolchain.yml
  examples/node-moon-monorepo/.moon/workspace.yml
  examples/node-moon-monorepo/package.json
  examples/node-moon-monorepo/packages/client/.eslintrc.json
  examples/node-moon-monorepo/packages/client/.gitignore
  examples/node-moon-monorepo/packages/client/README.md
  examples/node-moon-monorepo/packages/client/moon.yml
  examples/node-moon-monorepo/packages/client/next-env.d.ts
  examples/node-moon-monorepo/packages/client/next.config.js
  examples/node-moon-monorepo/packages/client/package.json
  examples/node-moon-monorepo/packages/client/pages/_app.tsx
  examples/node-moon-monorepo/packages/client/pages/api/hello.ts
  examples/node-moon-monorepo/packages/client/pages/index.tsx
  examples/node-moon-monorepo/packages/client/public/favicon.ico
  examples/node-moon-monorepo/packages/client/public/vercel.svg
  examples/node-moon-monorepo/packages/client/styles/Home.module.css
  examples/node-moon-monorepo/packages/client/styles/globals.css
  examples/node-moon-monorepo/packages/client/tsconfig.json
  examples/node-moon-monorepo/packages/server/.gitignore
  examples/node-moon-monorepo/packages/server/index.ts
  examples/node-moon-monorepo/packages/server/moon.yml
  examples/node-moon-monorepo/packages/server/package.json
  examples/node-moon-monorepo/packages/server/tsconfig.json
  examples/node-moon-monorepo/yarn.lock
  src/providers/node/mod.rs
  src/providers/node/moon.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__node_moon_monorepo.snap
Labels: release/minor

#945 Add support for custom host to docker client mapping in Docker builder
  docs/package.json
  docs/pages/docs/cli.md
  docs/pages/docs/deploying/pipeops.md
  docs/public/images/pipeops.png
  src/main.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
  src/nixpacks/builder/docker/mod.rs
  tests/docker_run_tests.rs
Labels: release/minor

#970 update global nixpkgs archive
  examples/node-pnpm-custom-node-version/package.json
  examples/node-yarn-custom-node-version/package.json
  examples/zig/.gitignore
  examples/zig/build.zig
  examples/zig/src/main.zig
  src/nixpacks/nix/mod.rs
  src/providers/clojure.rs
  src/providers/zig.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__clojure.snap
  tests/snapshots/generate_plan_tests__clojure_jdk11.snap
  tests/snapshots/generate_plan_tests__clojure_jdk_latest.snap
  tests/snapshots/generate_plan_tests__clojure_ring_app.snap
  tests/snapshots/generate_plan_tests__clojure_tools_build.snap
  tests/snapshots/generate_plan_tests__node_pnpm_custom_node_version.snap
  tests/snapshots/generate_plan_tests__node_yarn_custom_node_version.snap
  tests/snapshots/generate_plan_tests__zig.snap
Labels: release/minor

#972 Update default node version to 18
  examples/node-custom-version/package-lock.json
  examples/node-custom-version/package.json
  examples/node-pnpm-custom-node-version/pnpm-lock.yaml
  examples/node-turborepo/package.json
  src/providers/node/mod.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__multiple_providers.snap
  tests/snapshots/generate_plan_tests__nested.snap
  tests/snapshots/generate_plan_tests__node.snap
  tests/snapshots/generate_plan_tests__node_canvas.snap
  tests/snapshots/generate_plan_tests__node_custom_cache_directories.snap
  tests/snapshots/generate_plan_tests__node_custom_version.snap
  tests/snapshots/generate_plan_tests__node_legacy_prisma.snap
  tests/snapshots/generate_plan_tests__node_main_file.snap
  tests/snapshots/generate_plan_tests__node_main_file_not_exist.snap
  tests/snapshots/generate_plan_tests__node_monorepo.snap
  tests/snapshots/generate_plan_tests__node_moon_monorepo.snap
  tests/snapshots/generate_plan_tests__node_no_scripts.snap
  tests/snapshots/generate_plan_tests__node_npm.snap
  tests/snapshots/generate_plan_tests__node_npm_old_lockfile.snap
  tests/snapshots/generate_plan_tests__node_npm_v9.snap
  tests/snapshots/generate_plan_tests__node_nvmrc.snap
  tests/snapshots/generate_plan_tests__node_nx.snap
  tests/snapshots/generate_plan_tests__node_pnpm.snap
  tests/snapshots/generate_plan_tests__node_pnpm_custom_node_version.snap
  tests/snapshots/generate_plan_tests__node_pnpm_v7.snap
  tests/snapshots/generate_plan_tests__node_pnpm_v8.snap
  tests/snapshots/generate_plan_tests__node_prisma_postgres.snap
  tests/snapshots/generate_plan_tests__node_prisma_postgres_npm_v9.snap
  tests/snapshots/generate_plan_tests__node_puppeteer.snap
  tests/snapshots/generate_plan_tests__node_python.snap
  tests/snapshots/generate_plan_tests__node_turborepo.snap
  tests/snapshots/generate_plan_tests__node_typescript_incremental.snap
  tests/snapshots/generate_plan_tests__node_typescript_incremental_extends.snap
  tests/snapshots/generate_plan_tests__node_typescript_incremental_out_dir.snap
  tests/snapshots/generate_plan_tests__node_typescript_incremental_tsbuildinfo_path.snap
  tests/snapshots/generate_plan_tests__node_variables.snap
  tests/snapshots/generate_plan_tests__node_yarn.snap
  tests/snapshots/generate_plan_tests__node_yarn_berry.snap
  tests/snapshots/generate_plan_tests__node_yarn_custom_node_version.snap
  tests/snapshots/generate_plan_tests__node_yarn_prisma.snap
  tests/snapshots/generate_plan_tests__overriding_environment_variables.snap
  tests/snapshots/generate_plan_tests__php_laravel.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_json.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_mongodb.snap
  tests/snapshots/generate_plan_tests__procfile.snap
  tests/snapshots/generate_plan_tests__ruby_execjs.snap
  tests/snapshots/generate_plan_tests__ruby_with_node.snap
Labels: release/minor

#973 Update ruby.md
  docs/pages/docs/providers/ruby.md
Labels: release/skip

#981 Update node.md - fix version info
  docs/pages/docs/providers/node.md
Labels: release/skip

#983 Update sidebar.ts
  docs/pages/docs/providers/ruby.md
  docs/sidebar.ts
Labels: release/skip

#984 Fix apt-get glibc error
  examples/apt-ffmpeg/nixpacks.toml
  src/nixpacks/builder/docker/dockerfile_generation.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__apt_ffmpeg.snap
Labels: release/patch
