Repository railwayapp/nixpacks, pull requests merged in 2023-07, with the labels that each got.

#916 ref(deno): Add support for deno.jsonc and index.{tsx,jsx}
  docs/pages/docs/providers/deno.md
  src/providers/deno.rs
  tests/snapshots/generate_plan_tests__deno_fresh.snap
Labels: release/minor

#917 Rails: detect usage of sprockets/propshaft in lockfile, not just gemfile
  src/providers/ruby.rs
Labels: release/minor

#922 Add PDM support for Python projects
  docs/pages/docs/providers/python.md
  examples/python-pdm/.gitignore
  examples/python-pdm/main.py
  examples/python-pdm/pdm.lock
  examples/python-pdm/pyproject.toml
  src/providers/python.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__python_pdm.snap
Labels: release/minor

#928 Warn about missing environment variables for Laravel projects
  src/nixpacks/plan/mod.rs
  src/providers/node/mod.rs
  src/providers/php/Nixpacks/Util/Laravel.pm
  src/providers/php/Nixpacks/Util/Logger.pm
  src/providers/php/mod.rs
  src/providers/php/prestart.pl
  tests/snapshots/generate_plan_tests__php_custom_config.snap
  tests/snapshots/generate_plan_tests__php_laravel.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_json.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_mongodb.snap
  tests/snapshots/generate_plan_tests__php_vanilla.snap
Labels: release/patch

#927 add Coherence as a supported nixpacks builder
  docs/pages/docs/deploying/coherence.md
  docs/public/images/coherence.png
Labels: release/skip

#936 support new nx package names
  src/providers/node/nx.rs
Labels: release/patch
