Repository railwayapp/nixpacks, pull requests merged in 2023-01, with the labels that each got.

#755 allow insecure nix package installs
  base/debian/Dockerfile
  base/ubuntu/Dockerfile
Labels: release/patch

#756 use latest base debian and ubuntu images
  base/debian/Dockerfile
  base/ubuntu/Dockerfile
Labels: release/skip

#757 update ubuntu base image on schedule
  .github/workflows/publish_ubuntu.yml
Labels: release/skip

#727 Install ruby with rbenv
  src/providers/ruby.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__ruby.snap
  tests/snapshots/generate_plan_tests__ruby_2.snap
  tests/snapshots/generate_plan_tests__ruby_execjs.snap
  tests/snapshots/generate_plan_tests__ruby_local_deps.snap
  tests/snapshots/generate_plan_tests__ruby_rails_postgres.snap
  tests/snapshots/generate_plan_tests__ruby_sinatra.snap
  tests/snapshots/generate_plan_tests__ruby_with_node.snap
Labels: release/minor

#762 Ruby Version Envvar
  src/providers/ruby.rs
Labels: release/patch

#763 Use ubuntu image for all Ruby
  src/providers/ruby.rs
Labels: release/minor

#765 cargo snapshot alias
  .cargo/config.toml
  CONTRIBUTING.md
Labels: release/skip

#764 Use OpenSSL 1.1 for Debian base image
  docs/pages/docs/configuration/environment.md
  examples/node-legacy-prisma/.gitignore
  examples/node-legacy-prisma/nixpacks.toml
  examples/node-legacy-prisma/package.json
  examples/node-legacy-prisma/prisma/dev.db
  examples/node-legacy-prisma/prisma/dev.db-journal
  examples/node-legacy-prisma/prisma/migrations/20220427185714_init/migration.sql
  examples/node-legacy-prisma/prisma/migrations/migration_lock.toml
  examples/node-legacy-prisma/prisma/schema.prisma
  examples/node-legacy-prisma/src/index.ts
  examples/node-legacy-prisma/tsconfig.json
  examples/node-legacy-prisma/yarn.lock
  src/nixpacks/nix/mod.rs
  src/nixpacks/plan/mod.rs
  src/nixpacks/plan/phase.rs
  tests/snapshots/generate_plan_tests__node_legacy_prisma.snap
Labels: release/patch

#772 Fix lint issues
  .cargo/config.toml
  src/main.rs
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/nixpacks/builder/docker/incremental_cache.rs
  src/nixpacks/builder/docker/utils.rs
  src/nixpacks/nix/mod.rs
  src/providers/csharp.rs
  src/providers/fsharp.rs
  src/providers/java.rs
  src/providers/php/mod.rs
  src/providers/python.rs
  src/providers/ruby.rs
  src/providers/rust.rs
  src/providers/swift.rs
  src/providers/zig.rs
  tests/docker_run_tests.rs
  tests/generate_plan_tests.rs
Labels: release/skip

#773 Fix typo
  docs/pages/docs/providers/node.md
Labels: release/skip

#771 Add support for Clojure `tools.build` projects
  docs/pages/docs/providers/clojure.md
  examples/clojure-tools-build/.gitignore
  examples/clojure-tools-build/DOCKERFILE
  examples/clojure-tools-build/build.clj
  examples/clojure-tools-build/deps.edn
  examples/clojure-tools-build/src/clojure_example/core.clj
  src/providers/clojure.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__clojure_tools_build.snap
Labels: release/patch

#774 Fix some spellling in `docs`
  docs/pages/docs/providers/clojure.md
  docs/pages/docs/providers/elixir.md
  docs/pages/docs/providers/java.md
  docs/pages/docs/providers/node.md
  docs/pages/docs/providers/python.md
  docs/pages/docs/providers/swift.md
Labels: release/skip

#766 feat(csharp): allow configurable sdk version
  .cargo/config.toml
  docs/pages/docs/providers/csharp.md
  examples/csharp-api/global.json
  src/providers/csharp.rs
  tests/snapshots/generate_plan_tests__csharp_api.snap
Labels: release/minor
