Repository railwayapp/nixpacks, pull requests merged in 2023-02, with the labels that each got.

#780 feat: add support for multiple rust binaries
  docs/pages/docs/providers/rust.md
  src/providers/rust.rs
Labels: release/minor

#781 docker run test for rust with multiple bins
  examples/rust-multiple-bins/.gitignore
  examples/rust-multiple-bins/Cargo.toml
  examples/rust-multiple-bins/src/bin/bin1.rs
  examples/rust-multiple-bins/src/bin/bin2.rs
  test-helper/src/lib.rs
  tests/docker_run_tests.rs
Labels: release/skip

#782 feat(scala): Added ScalaProvider
  docs/pages/docs/providers/scala.md
  docs/sidebar.ts
  examples/scala-sbt/.gitignore
  examples/scala-sbt/build.sbt
  examples/scala-sbt/project/build.properties
  examples/scala-sbt/project/plugins.sbt
  examples/scala-sbt/src/main/scala/Main.scala
  src/lib.rs
  src/providers/mod.rs
  src/providers/scala.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__scala_sbt.snap
Labels: release/minor

#785 Improve NX docs
  docs/pages/docs/providers/node.md
Labels: release/skip

#799 Fix powershell permanent redirect
  docs/next.config.js
Labels: release/skip

#787 Rust: support top-level main bin
  examples/rust-multiple-bins/src/main.rs
  src/providers/rust.rs
  tests/generate_plan_tests.rs
Labels: release/patch

#801 Cache rust dependencies in test suite
  .github/workflows/ci.yml
Labels: release/skip

#795 Fix SDK version parsing
  src/providers/csharp.rs
  tests/snapshots/generate_plan_tests__csharp_api.snap
Labels: release/patch

#796 Merge publish workflows into one
  .github/workflows/publish.yml
  .github/workflows/publish_ubuntu.yml
Labels: release/skip

#789 feat(scala): reduced scala sbt image size
  src/providers/scala.rs
  tests/snapshots/generate_plan_tests__scala_sbt.snap
Labels: release/patch

#797 Support nested directories
  examples/nested/hello/sub/index.js
  examples/nested/hello/sub/package.json
  src/lib.rs
  src/nixpacks/plan/generator.rs
  src/nixpacks/plan/mod.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__nested.snap
Labels: release/patch
