Repository railwayapp/nixpacks, pull requests merged in 2023-12, with the labels that each got.

#1028 docs: add label with value example
  docs/pages/docs/cli.md
Labels: release/skip

#1029 Fix typos on configuring-builds.md
  docs/pages/docs/guides/configuring-builds.md
Labels: release/skip

#1019 Update Go versions
  docs/pages/docs/providers/go.md
  src/providers/go.rs
Labels: release/minor

#1022 [php] add checkEnvErrors to the main Promise.all()
  src/providers/php/scripts/prestart.mjs
  tests/snapshots/generate_plan_tests__php_api.snap
  tests/snapshots/generate_plan_tests__php_custom_config.snap
  tests/snapshots/generate_plan_tests__php_laravel.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_json.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_mongodb.snap
  tests/snapshots/generate_plan_tests__php_vanilla.snap
Labels: release/patch

#1020 Add support for Java 20/21 in Java & Scala Providers
  docs/pages/docs/providers/java.md
  docs/pages/docs/providers/scala.md
  src/providers/java.rs
  src/providers/scala.rs
  tests/snapshots/generate_plan_tests__scala_sbt.snap
Labels: release/minor
