Repository railwayapp/nixpacks, pull requests merged in 2024-05, with the labels that each got.

#1101 docs: update nixos link to official wiki
  docs/pages/docs/configuration/file.md
Labels: release/skip

#1100 improved default python vars
  docs/pages/docs/providers/python.md
  src/providers/python.rs
  tests/snapshots/generate_plan_tests__multiple_providers.snap
  tests/snapshots/generate_plan_tests__node_python.snap
  tests/snapshots/generate_plan_tests__python.snap
  tests/snapshots/generate_plan_tests__python_2.snap
  tests/snapshots/generate_plan_tests__python_2_runtime.snap
  tests/snapshots/generate_plan_tests__python_django.snap
  tests/snapshots/generate_plan_tests__python_django_mysql.snap
  tests/snapshots/generate_plan_tests__python_django_pipfile.snap
  tests/snapshots/generate_plan_tests__python_numpy.snap
  tests/snapshots/generate_plan_tests__python_pdm.snap
  tests/snapshots/generate_plan_tests__python_poetry.snap
  tests/snapshots/generate_plan_tests__python_postgres.snap
  tests/snapshots/generate_plan_tests__python_procfile.snap
  tests/snapshots/generate_plan_tests__python_setuptools.snap
Labels: release/patch

#1083 Update `pdm` to latest
  src/providers/python.rs
  tests/snapshots/generate_plan_tests__python_pdm.snap
Labels: release/minor

#1106 update nix archive version used for node and bun
  examples/multiple-providers/nixpacks.toml
  examples/node-canvas/package-lock.json
  examples/node-canvas/package.json
  examples/node-custom-version/package.json
  src/providers/node/mod.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__multiple_providers.snap
  tests/snapshots/generate_plan_tests__node_canvas.snap
  tests/snapshots/generate_plan_tests__node_custom_version.snap
  tests/snapshots/generate_plan_tests__node_pnpm_custom_node_version.snap
  tests/snapshots/generate_plan_tests__node_turborepo.snap
Labels: release/minor

#1096 Add support for go 1.22
  docs/pages/docs/providers/go.md
  src/providers/go.rs
Labels: release/minor

#1079 fix(node/moon): use cli @moonrepo/cli name if pnpx executable is run
  examples/node-moon-monorepo/package-lock.json
  examples/node-moon-monorepo/package.json
  examples/node-moon-monorepo/yarn.lock
  src/providers/node/moon.rs
  tests/snapshots/generate_plan_tests__node_moon_monorepo.snap
Labels: release/patch, stale

#1107 Support Python 3.12
  src/providers/python.rs
Labels: release/minor

#1111 add dokploy in deploying section
  docs/pages/docs/deploying/dokploy.md
  docs/public/images/dokploy.png
  docs/sidebar.ts
Labels: release/skip

#1113 Support Bun 1.1.9
  src/providers/node/mod.rs
Labels: release/patch
