Repository railwayapp/nixpacks, pull requests merged in 2024-11, with the labels that each got.

#1206 fix: cairo as lib and not package
  src/providers/python.rs
Labels: release/patch

#1198 Add Haunt for Scheme as a provider
  docs/pages/docs/providers/scheme.md
  docs/sidebar.ts
  examples/scheme/haunt.scm
  examples/scheme/init.scm
  src/lib.rs
  src/providers/mod.rs
  src/providers/scheme.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__scheme.snap
Labels: release/minor

#1215 determinstic procfile selection
  docs/pages/docs/configuration/procfile.md
  src/providers/procfile.rs
Labels: release/patch

#1218 Add support for Go 1.23
  docs/pages/docs/providers/go.md
  examples/go-v123/go.mod
  examples/go-v123/main.go
  src/providers/go.rs
  tests/snapshots/generate_plan_tests__go_v123.snap
Labels: release/minor

#1219 dokku docs
  docs/pages/docs/deploying/dokku.md
  docs/sidebar.ts
Labels: release/skip

#1207 fix: better elixir docs and defaults
  docs/pages/docs/providers/elixir.md
  src/providers/elixir.rs
  tests/snapshots/generate_plan_tests__elixir_ecto.snap
  tests/snapshots/generate_plan_tests__elixir_phx_no_ecto.snap
Labels: release/patch

#1193 support running with custom non-root user
  examples/custom-user/nixpacks.toml
  examples/custom-user/start.sh
  src/nixpacks/builder/docker/dockerfile_generation.rs
  src/nixpacks/plan/merge.rs
  src/nixpacks/plan/phase.rs
  tests/snapshots/generate_plan_tests__custom_user.snap
Labels: release/minor

#1220 multi arch docs
  docs/pages/docs/guides/configuring-builds.md
Labels: release/skip

#1225 feat(php): ignore multiple php extensions
  src/providers/php/mod.rs
Labels: release/patch

#1223 feat: node 23, more recent patch versions'
  Makefile
  examples/node-prisma-postgres/package-lock.json
  examples/node-prisma-postgres/package.json
  examples/node-yarn-prisma/package.json
  examples/node-yarn-prisma/yarn.lock
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_pnpm_corepack.snap
  tests/snapshots/generate_plan_tests__node_prisma_postgres.snap
  tests/snapshots/generate_plan_tests__node_turborepo.snap
Labels: release/minor
