Repository railwayapp/nixpacks, pull requests merged in 2024-08, with the labels that each got.

#1161 Fix custom rust toolchain test
  examples/rust-custom-toolchain/rust-toolchain.toml
  tests/docker_run_tests.rs
Labels: release/skip

#1158 fix name of procfile provider
  src/providers/procfile.rs
Labels: release/patch

#1152 Support Bun 1.1.20
  src/providers/node/mod.rs
Labels: release/patch

#1163 Only check if docker exists if building
  src/lib.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
Labels: release/patch

#1166 Trim environment variable names when adding to Dockerfile
  src/nixpacks/builder/docker/dockerfile_generation.rs
Labels: release/minor

#1165 Feat/docker cert path
  docs/pages/docs/cli.md
  src/main.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
  src/nixpacks/builder/docker/mod.rs
Labels: release/minor

#1169 Add doc on how to add PHP extensions + details on the server root
  docs/pages/docs/providers/php.md
Labels: release/skip

#1172 Support PNPM 9
  examples/node-pnpm-corepack/.gitignore
  examples/node-pnpm-corepack/index.ts
  examples/node-pnpm-corepack/package.json
  examples/node-pnpm-corepack/pnpm-lock.yaml
  examples/node-pnpm-corepack/tsconfig.json
  examples/node-pnpm-custom-node-version/index.ts
  examples/node-pnpm-custom-node-version/pnpm-lock.yaml
  examples/node-pnpm-v6/.gitignore
  examples/node-pnpm-v6/index.ts
  examples/node-pnpm-v6/package.json
  examples/node-pnpm-v6/pnpm-lock.yaml
  examples/node-pnpm-v6/tsconfig.json
  examples/node-pnpm-v7/index.ts
  examples/node-pnpm-v7/pnpm-lock.yaml
  examples/node-pnpm-v9/.gitignore
  examples/node-pnpm-v9/index.ts
  examples/node-pnpm-v9/package.json
  examples/node-pnpm-v9/pnpm-lock.yaml
  examples/node-pnpm-v9/tsconfig.json
  examples/node-pnpm/index.ts
  src/providers/node/mod.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__node_pnpm_corepack.snap
  tests/snapshots/generate_plan_tests__node_pnpm_v6.snap
  tests/snapshots/generate_plan_tests__node_pnpm_v9.snap
Labels: release/minor

#1168 [PHP Provider] Ensure that PHP-FPM workers output is streamed to Nginx
  src/providers/php/php-fpm.conf
  tests/snapshots/generate_plan_tests__php_api.snap
  tests/snapshots/generate_plan_tests__php_custom_config.snap
  tests/snapshots/generate_plan_tests__php_laravel.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_json.snap
  tests/snapshots/generate_plan_tests__php_laravel_ext_mongodb.snap
  tests/snapshots/generate_plan_tests__php_vanilla.snap
Labels: release/patch
