Repository railwayapp/nixpacks, pull requests merged in 2024-09, with the labels that each got.

#1178 fix: automatically add cairo lib dependency when pip package is detected
  src/providers/python.rs
Labels: release/minor

#1175 Remove redundant line from test_phase_generation
  src/nixpacks/builder/docker/dockerfile_generation.rs
Labels: release/skip

#1177 Fix fill_auto_in_vec function doc test
  src/nixpacks/plan/mod.rs
  src/nixpacks/plan/utils.rs
Labels: release/patch

#1180 set all docker envs on command
  src/nixpacks/builder/docker/docker_image_builder.rs
Labels: release/patch

#1174 update cargo_toml dependency
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  README.md
  examples/config-toml-file/nixpacks.toml
  flake.lock
  flake.nix
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__config_toml_file.snap
Labels: release/patch

#1183 Resolve build warning for LegacyKeyValueFormat
  src/nixpacks/builder/docker/dockerfile_generation.rs
Labels: release/patch

#1186 actually use the docker-output flag
  src/main.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
Labels: release/patch

#1155 fix: do not mutate read-only files
  src/nixpacks/files.rs
Labels: release/patch

#1195 Update install steps in getting-started.md
  docs/pages/docs/getting-started.md
Labels: release/skip
