Repository railwayapp/nixpacks, pull requests merged in 2024-07, with the labels that each got.

#1116 feat: asdf support
  examples/python-asdf-poetry/.tool-versions
  examples/python-asdf-poetry/main.py
  examples/python-asdf-poetry/poetry.lock
  examples/python-asdf-poetry/pyproject.toml
  src/nixpacks/asdf.rs
  src/nixpacks/mod.rs
  src/providers/python.rs
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__python_asdf_poetry.snap
Labels: release/patch, stale

#1120 fix available / not available versions
  docs/pages/docs/providers/node.md
  docs/pages/docs/providers/php.md
  docs/pages/docs/providers/python.md
Labels: release/patch, stale

#1123 Add Gleam To Sidebar
  docs/sidebar.ts
Labels: release/patch, stale

#1125 Fix typo in base image
  src/providers/scala.rs
Labels: release/patch, stale

#1115 feat: dump build command when --out is specified
  src/nixpacks/builder/docker/docker_image_builder.rs
Labels: release/patch

#1121 docs: adding nixpacks github action
  docs/pages/docs/deploying/dokploy.md
  docs/pages/docs/deploying/github-actions.md
  docs/sidebar.ts
Labels: release/skip

#1127 feat(tests): better cleanup on docker tests
  CONTRIBUTING.md
  tests/docker_run_tests.rs
Labels: release/patch

#1119 Support for --add-host
  Cargo.lock
  examples/node-fetch-network/.gitignore
  examples/node-fetch-network/fetchData.js
  examples/node-fetch-network/package.json
  examples/node-fetch-network/pnpm-lock.yaml
  src/main.rs
  src/nixpacks/builder/docker/docker_helper.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
  src/nixpacks/builder/docker/incremental_cache.rs
  src/nixpacks/builder/docker/mod.rs
  test-helper/Cargo.toml
  tests/docker_run_tests.rs
  tests/snapshots/generate_plan_tests__node_fetch_network.snap
Labels: release/minor

#1150 support Docker `--output` argument
  src/main.rs
  src/nixpacks/builder/docker/docker_image_builder.rs
  src/nixpacks/builder/docker/mod.rs
Labels: release/minor
