Repository railwayapp/nixpacks, pull requests merged in 2024-02, with the labels that each got.

#1056 Update environment.md
  docs/pages/docs/configuration/environment.md
Labels: release/skip

#1051 Update newly available version in docs
  docs/pages/docs/providers/php.md
Labels: stale

#1052 fix: automatically add gcc-unwrapped when installing sharp
  docs/pages/docs/guides/configuring-builds.md
  src/providers/node/mod.rs
Labels: release/patch

#1055 fix: add correct libs if canvas and puppeteer are setup
  src/providers/node/mod.rs
Labels: release/patch

#1070 pin corepack to 0.24.1
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_yarn_berry.snap
Labels: release/patch
