Repository railwayapp/nixpacks, pull requests merged in 2025-04, with the labels that each got.

#1298 Update php.md
  docs/pages/docs/providers/php.md
Labels: release/skip

#1306 Docs(Deploying): add justdeploy as Deploying solution
  docs/pages/docs/deploying/justdeploy.md
Labels: release/skip

#1307 docs(deploying): add Justdeploy to sidebar
  docs/pages/docs/deploying/justdeploy.md
  docs/sidebar.ts
Labels: release/skip

#1313 lint fix
  src/nixpacks/app.rs
  src/nixpacks/plan/merge.rs
  src/providers/deno.rs
  src/providers/node/mod.rs
  src/providers/node/turborepo.rs
  src/providers/php/mod.rs
  src/providers/procfile.rs
Labels: release/skip

#1311 Fix ubuntu noble base image
  .github/workflows/publish.yml
  base/ubuntu/Dockerfile
  src/nixpacks/images.rs
  src/providers/node/turborepo.rs
  tests/snapshots/generate_plan_tests__go.snap
  tests/snapshots/generate_plan_tests__go_cmd.snap
  tests/snapshots/generate_plan_tests__go_custom_version.snap
  tests/snapshots/generate_plan_tests__go_gin.snap
  tests/snapshots/generate_plan_tests__go_mod.snap
  tests/snapshots/generate_plan_tests__go_v123.snap
Labels: release/minor

#1314 fix debian dockerfile
  base/debian/Dockerfile
Labels: release/patch

#1303 Fix/fix react router v7 application building
  docs/pages/docs/providers/node.md
  examples/node-react-router-v7-framework/.dockerignore
  examples/node-react-router-v7-framework/.gitignore
  examples/node-react-router-v7-framework/Dockerfile
  examples/node-react-router-v7-framework/README.md
  examples/node-react-router-v7-framework/app/app.css
  examples/node-react-router-v7-framework/app/root.tsx
  examples/node-react-router-v7-framework/app/routes.ts
  examples/node-react-router-v7-framework/app/routes/home.tsx
  examples/node-react-router-v7-framework/app/welcome/logo-dark.svg
  examples/node-react-router-v7-framework/app/welcome/logo-light.svg
  examples/node-react-router-v7-framework/app/welcome/welcome.tsx
  examples/node-react-router-v7-framework/package.json
  examples/node-react-router-v7-framework/public/favicon.ico
  examples/node-react-router-v7-framework/react-router.config.ts
  examples/node-react-router-v7-framework/tsconfig.json
  examples/node-react-router-v7-framework/vite.config.ts
  examples/node-react-router-v7-spa/.gitignore
  examples/node-react-router-v7-spa/README.md
  examples/node-react-router-v7-spa/eslint.config.js
  examples/node-react-router-v7-spa/index.html
  examples/node-react-router-v7-spa/package-lock.json
  examples/node-react-router-v7-spa/package.json
  examples/node-react-router-v7-spa/public/vite.svg
  examples/node-react-router-v7-spa/src/App.css
  examples/node-react-router-v7-spa/src/App.tsx
  examples/node-react-router-v7-spa/src/assets/react.svg
  examples/node-react-router-v7-spa/src/index.css
  examples/node-react-router-v7-spa/src/main.tsx
  examples/node-react-router-v7-spa/src/vite-env.d.ts
  examples/node-react-router-v7-spa/tsconfig.app.json
  examples/node-react-router-v7-spa/tsconfig.json
  examples/node-react-router-v7-spa/tsconfig.node.json
  examples/node-react-router-v7-spa/vite.config.ts
  src/providers/node/spa/vite.rs
  src/providers/rust.rs
  tests/snapshots/generate_plan_tests__node_react_router_v7_framework.snap
  tests/snapshots/generate_plan_tests__node_react_router_v7_spa.snap
Labels: release/patch

#1312 Separate nix archive specifically for bun
  src/providers/node/mod.rs
Labels: release/minor

#1316 add back missing env vars to base images
  base/debian/Dockerfile
  base/ubuntu/Dockerfile
Labels: release/skip

#1320 revert rust musl behaviour
  src/providers/rust.rs
Labels: release/patch
