Repository railwayapp/nixpacks, pull requests merged in 2025-01, with the labels that each got.

#1245 Add support for bun.lock
  src/providers/node/mod.rs
Labels: release/patch

#1234 feat(jsonc): added jsonc support
  examples/deno-jsonc/deno.jsonc
  examples/deno-jsonc/deno.lock
  examples/deno-jsonc/main.ts
  examples/deno-jsonc/main_test.ts
  src/nixpacks/app.rs
  src/providers/deno.rs
  tests/snapshots/generate_plan_tests__deno_jsonc.snap
Labels: release/minor

#1235 Add .node-version file basic support
  examples/node-node-version/.node-version
  examples/node-node-version/index.js
  examples/node-node-version/package-lock.json
  examples/node-node-version/package.json
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_node_version.snap
Labels: release/minor

#1242 Fix #1241: nixpack plan generates an invalid toml file ...
  src/providers/python.rs
Labels: release/patch

#1251 node env clarification
  docs/pages/docs/providers/node.md
Labels: release/patch

#1249 fix(plan): stdout logic for valid output files
  docs/pages/docs/cli.md
  src/main.rs
  src/providers/node/mod.rs
  src/providers/node/turborepo.rs
  src/providers/php/mod.rs
  src/providers/python.rs
Labels: release/patch

#1232 feat: add support for cmd directories in golang
  docs/pages/docs/providers/go.md
  examples/go-cmd/.gitignore
  examples/go-cmd/cmd/server/main.go
  examples/go-cmd/go.mod
  examples/go-cmd/go.sum
  examples/go-gin/cmd/server/main.go
  src/providers/go.rs
  tests/snapshots/generate_plan_tests__go_cmd.snap
Labels: release/minor, stale

#1256 Add Stacktape into deploy docs
  docs/pages/docs/deploying/stacktape.md
  docs/public/images/stacktape.png
Labels: release/skip

#1260 fix clipply lints
  examples/lunatic-basic/Cargo.toml
  src/nixpacks/environment.rs
  src/providers/clojure.rs
  src/providers/cobol.rs
  src/providers/crystal.rs
  src/providers/csharp.rs
  src/providers/dart.rs
  src/providers/deno.rs
  src/providers/elixir.rs
  src/providers/fsharp.rs
  src/providers/gleam/mod.rs
  src/providers/go.rs
  src/providers/haskell.rs
  src/providers/java.rs
  src/providers/lunatic.rs
  src/providers/node/mod.rs
  src/providers/php/mod.rs
  src/providers/procfile.rs
  src/providers/python.rs
  src/providers/ruby.rs
  src/providers/rust.rs
  src/providers/scala.rs
  src/providers/scheme.rs
  src/providers/staticfile.rs
  src/providers/swift.rs
  src/providers/zig.rs
  tests/snapshots/generate_plan_tests__lunatic_basic.snap
Labels: release/skip

#1258 Select latest lts node version
  src/providers/node/mod.rs
  tests/snapshots/generate_plan_tests__node_pnpm_corepack.snap
  tests/snapshots/generate_plan_tests__node_turborepo.snap
Labels: release/patch

#1261 Update Nix archive for Rust
  examples/lunatic-basic/.cargo/config.toml
  examples/lunatic-basic/Cargo.toml
  examples/lunatic-basic/src/main.rs
  src/providers/rust.rs
  tests/docker_run_tests.rs
Labels: release/minor

#1264 Add Stacktape deploy option page to docs sidebar.
  docs/sidebar.ts
Labels: release/skip

#1262 Add Coolify as Nixpacks is available as a builder on it
  docs/pages/docs/deploying/coolify.md
  docs/public/images/coolify.png
  docs/sidebar.ts
Labels: release/skip

#1263 feat: use `packageManager` as a attempt to identify node package manager
  docs/pages/docs/providers/node.md
  examples/node-pnpm-monorepo/.eslintrc.js
  examples/node-pnpm-monorepo/.gitignore
  examples/node-pnpm-monorepo/apps/docs/.eslintrc.js
  examples/node-pnpm-monorepo/apps/docs/README.md
  examples/node-pnpm-monorepo/apps/docs/next-env.d.ts
  examples/node-pnpm-monorepo/apps/docs/next.config.js
  examples/node-pnpm-monorepo/apps/docs/package.json
  examples/node-pnpm-monorepo/apps/docs/pages/index.tsx
  examples/node-pnpm-monorepo/apps/docs/tsconfig.json
  examples/node-pnpm-monorepo/apps/web/.eslintrc.js
  examples/node-pnpm-monorepo/apps/web/README.md
  examples/node-pnpm-monorepo/apps/web/next-env.d.ts
  examples/node-pnpm-monorepo/apps/web/next.config.js
  examples/node-pnpm-monorepo/apps/web/package.json
  examples/node-pnpm-monorepo/apps/web/pages/index.tsx
  examples/node-pnpm-monorepo/apps/web/tsconfig.json
  examples/node-pnpm-monorepo/package.json
  examples/node-pnpm-monorepo/packages/eslint-config-custom/index.js
  examples/node-pnpm-monorepo/packages/eslint-config-custom/package.json
  examples/node-pnpm-monorepo/packages/tsconfig/README.md
  examples/node-pnpm-monorepo/packages/tsconfig/base.json
  examples/node-pnpm-monorepo/packages/tsconfig/nextjs.json
  examples/node-pnpm-monorepo/packages/tsconfig/package.json
  examples/node-pnpm-monorepo/packages/tsconfig/react-library.json
  examples/node-pnpm-monorepo/packages/ui/Button.tsx
  examples/node-pnpm-monorepo/packages/ui/index.tsx
  examples/node-pnpm-monorepo/packages/ui/package.json
  examples/node-pnpm-monorepo/packages/ui/tsconfig.json
  examples/node-pnpm-monorepo/pnpm-lock.yaml
  examples/node-pnpm-monorepo/pnpm-workspace.yaml
  src/providers/node/mod.rs
Labels: release/minor

#1266 Support PHP 8.4
  examples/php-laravel-84/.editorconfig
  examples/php-laravel-84/.env.example
  examples/php-laravel-84/.gitattributes
  examples/php-laravel-84/.gitignore
  examples/php-laravel-84/README.md
  examples/php-laravel-84/app/Http/Controllers/Controller.php
  examples/php-laravel-84/app/Models/User.php
  examples/php-laravel-84/app/Providers/AppServiceProvider.php
  examples/php-laravel-84/artisan
  examples/php-laravel-84/bootstrap/app.php
  examples/php-laravel-84/bootstrap/cache/.gitignore
  examples/php-laravel-84/bootstrap/providers.php
  examples/php-laravel-84/composer.json
  examples/php-laravel-84/composer.lock
  examples/php-laravel-84/config/app.php
  examples/php-laravel-84/config/auth.php
  examples/php-laravel-84/config/cache.php
  examples/php-laravel-84/config/database.php
  examples/php-laravel-84/config/filesystems.php
  examples/php-laravel-84/config/logging.php
  examples/php-laravel-84/config/mail.php
  examples/php-laravel-84/config/queue.php
  examples/php-laravel-84/config/services.php
  examples/php-laravel-84/config/session.php
  examples/php-laravel-84/database/.gitignore
  examples/php-laravel-84/database/factories/UserFactory.php
  examples/php-laravel-84/database/migrations/0001_01_01_000000_create_users_table.php
  examples/php-laravel-84/database/migrations/0001_01_01_000001_create_cache_table.php
  examples/php-laravel-84/database/migrations/0001_01_01_000002_create_jobs_table.php
  examples/php-laravel-84/database/seeders/DatabaseSeeder.php
  examples/php-laravel-84/package.json
  examples/php-laravel-84/phpunit.xml
  examples/php-laravel-84/postcss.config.js
  examples/php-laravel-84/public/.htaccess
  examples/php-laravel-84/public/favicon.ico
  examples/php-laravel-84/public/index.php
  examples/php-laravel-84/public/robots.txt
  examples/php-laravel-84/resources/css/app.css
  examples/php-laravel-84/resources/js/app.js
  examples/php-laravel-84/resources/js/bootstrap.js
  examples/php-laravel-84/resources/views/welcome.blade.php
  examples/php-laravel-84/routes/console.php
  examples/php-laravel-84/routes/web.php
  examples/php-laravel-84/storage/app/.gitignore
  examples/php-laravel-84/storage/app/private/.gitignore
  examples/php-laravel-84/storage/app/public/.gitignore
  examples/php-laravel-84/storage/framework/.gitignore
  examples/php-laravel-84/storage/framework/cache/.gitignore
  examples/php-laravel-84/storage/framework/cache/data/.gitignore
  examples/php-laravel-84/storage/framework/sessions/.gitignore
  examples/php-laravel-84/storage/framework/views/.gitignore
  examples/php-laravel-84/storage/logs/.gitignore
  examples/php-laravel-84/tailwind.config.js
  examples/php-laravel-84/tests/Feature/ExampleTest.php
  examples/php-laravel-84/tests/TestCase.php
  examples/php-laravel-84/tests/Unit/ExampleTest.php
  examples/php-laravel-84/vite.config.js
  src/providers/php/mod.rs
  tests/snapshots/generate_plan_tests__php_laravel_84.snap
Labels: release/minor
